### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by larseggert** [ietf-tools/mailarch#3524] opened 2022-08-25 15:53 UTC
At least some of the links in the email at this archive URL are not working: https://mailarchive.ietf.org/arch/msg/ietf/dC4nxuB-Glom87-otfdBf_-Tu84/

For example, https://mailarchive.ietf.org/arch/msg/ietf-smtp/CneRIG1vjNNbFYPW-z7mtUXe8Ik/ returns "not found".

**Comment by rjsparks** [comment] 2022-08-25 15:56
duplicate of #3520 I think.

**Comment by rpcross** [comment] 2022-09-06 23:05
This is not related to #3520. I have checked and all 11 messages referenced here were removed from the archive in April of 2019. The message files themselves still exist on disk but don't appear in search. This would have been done at the direction of some leadership at the IETF, but I am unable to find any email correspondence showing this.

**Comment by larseggert** [comment] 2022-09-07 04:40
Do we have indication or documentation that other messages have been removed from the public archive?

**Comment by larseggert** [comment] 2022-09-07 17:10
Also, for all messages that were administratively removed, could we please add a tombstone saying that this is what happened, rather than simply letting the links go 404?

**Comment by rjsparks** [comment] 2022-09-07 17:25
I think the documentation exists only in the communication chain asking for things to happen. As Ryan demonstrates, that can be hard to relocate. The commands may very well have been given in slack.

It was a requirement at the time to not leave a tombstone. I don't remember why (but I'm guessing it was because of the optics at the time). Our experience with tombstones in the past is horrific. If we implement something like this, it should be UI, not a fake message, and it would require a new database model to inform when the UI should say something.

These are rare enough, though, please consider carefully whether we really want to make changes around them? They will come with very sharp edges.

**Comment by rjsparks** [comment] 2022-09-07 17:29
(Also, note that what I'm suggesting (not creating a fake replacement message) means that IMAP users wouldn't see the message at all.

**Comment by larseggert** [comment] 2022-09-07 17:42
I'm OK with IMAP users not seeing the removed messages.

But when we have supposedly archival links go 404, that looks like a bug and not something that is by design. 403, 401 or even 451 would at least be better return codes. And a web page saying "this email was removed from the public archive" would cause less confusion all around IMO.

**Comment by rjsparks** [comment] 2022-09-07 18:16
@rpcross what would we have to add to be able to return a message like Lars suggests?

**Comment by rpcross** [comment] 2022-09-07 18:55
It should not be too difficult to check for the presence of the file in the _removed directory, and if it's there respond with the message "This email was removed from the public archive". Should this be a 200, or one of the 4NN codes mentioned? Also, by far the predominant content in _removed is spam which we do not distinguish from messages removed due to abusive content. So these links would return the same message.

**Comment by rjsparks** [comment] 2022-09-08 17:18
The simple message you propose that doesn't distinguish _why_ things are removed is the right thing to do.
However, having a database of when/why somewhere could be useful, and maybe should be made part of the app (track this as a separate issue?)
410 Gone looks like the right response code to me.

**Comment by rpcross** [comment] 2022-12-16 23:47
Fixed in commit afaeff5402e0cfd3fa8e569e5e75b0bad3402b69

**Closed by rpcross** 2022-12-16 23:47 UTC
